export enum Level {
  BACHELORES = 'BACHELORES',
  MASTERS = 'MASTERS',
}

export enum FieldOfStudies {
  PEIT = 'PEIT',
  NAUTICAL = 'NAUTICAL',
  MECHANICAL = 'MECHANICAL',
  MANAGEMENT = 'MANAGEMENT',
  MARINA = 'MARINA',
}

export enum UserRole {
  PROFESSOR = 'PROFESSOR',
  STUDENT = 'STUDENT',
  ADMIN = 'ADMIN',
}

export enum ApplicationStatus {
  DRAFT = 'DRAFT',
  PENDING_MENTOR = 'PENDING_MENTOR',
  PENDING_ADMIN = 'PENDING_ADMIN',
  SCHEDULED = 'SCHEDULED',
  DONE = 'DONE',
  FAILED = 'FAILED',
}
