export enum ThesisLevel {
  BACHELORES = 'BACHELORES',
  MASTERS = 'MASTERS',
}

export enum FieldOfStudies {
  PEIT = 'PEIT',
  NAUTICAL = 'NAUTICAL',
  MECHANICAL = 'MECHANICAL',
  MANAGEMENT = 'MANAGEMENT',
  MARINA = 'MARINA',
}

export enum UserRole {
  PROFESSOR = 'PROFESSOR',
  STUDENT = 'STUDENT',
  OFFICE = 'OFFICE',
  ADMIN = 'ADMIN',
}

export enum ApplicationStatus {
  DRAFT = 'DRAFT',
  PENDING_MENTOR = 'PENDING_MENTOR',
  PENDING_OFFICE = 'PENDING_OFFICE',
  SCHEADULED = 'SCHEADULED',
  DONE = 'DONE',
  FAILED = 'FAILED',
}
